-- 001 · registrations
--
-- Applied by `npm run db:migrate`. Do not edit this file once it has run
-- anywhere real — the runner checksums applied migrations and will tell you it
-- changed. Add a new numbered file instead.

create table if not exists registrations (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  ref         text        not null unique,          -- SBC-4K9P, shown to the guest and put in the UPI note
  name        text        not null,
  phone       text        not null,                 -- 10 digits, no country code
  email       text        not null,
  gender      text        not null check (gender in ('male', 'female')),
  amount      integer     not null check (amount > 0), -- rupees, derived on the server from gender
  utr         text,                                 -- 12-digit UPI reference, self-reported by the guest
  utr_at      timestamptz,
  status      text        not null default 'pending'
                          check (status in ('pending', 'submitted', 'paid', 'cancelled')),
  -- pending   : registered, has not told us they paid
  -- submitted : guest entered a UTR. NOT verified. Do not treat as paid.
  -- paid      : a human matched the UTR against the bank statement
  -- cancelled : no-show / refunded / duplicate. Frees the spot.
  note        text                                  -- organiser's own note, admin only
);

create index if not exists registrations_created_at_idx on registrations (created_at desc);
create index if not exists registrations_status_idx     on registrations (status);

-- One person, one spot. Stops the double-tap duplicate and the "register twice
-- to hold two spots" trick, while still letting a cancelled row be re-registered.
create unique index if not exists registrations_phone_live_idx
  on registrations (phone)
  where status <> 'cancelled';

-- Note on access control: this database is reached only by this app's server
-- code over DATABASE_URL. There is no PostgREST, no public API and no anon key,
-- so there is no untrusted client to constrain with row-level security. Keep it
-- that way: never expose this database to the browser.
